examples: fix build error
fixed below build error to classification_profiling_schedule.cpp

/home/abuild/rpmbuild/BUILD/libcoa-v0.4.0/examples/cpp_classification/classification_profiling_schedule.cpp:92: undefined reference to `caffe::AclEnableSchedule(int)'

Calling AclEnableSchedule function isn't required
becasue Caff::set_mode function is called already.

Signed-off-by: Inki Dae <inki.dae@samsung.com>